// render/src/components/VirtualList.svelte
<script lang="ts">
import { onMount, tick, onDestroy } from 'svelte'

export let list;
export let keeps = 30;
export let itemHeight = 60;

let listWrapper;
let scrollOffset = 0;
let start = 0;
let totalHeight = 0;
let paddingBottom = 0;

let offset = 0;

$: {
  totalHeight = list.length * itemHeight
  offset = 0
  start = 0
  scrollOffset = 0
}
$: {
  visibleList = list.slice(start, start + keeps)
}
$: {
  paddingBottom = totalHeight-scrollOffset-itemHeight*keeps
}

let visibleList = [];

const scrollDownHandler = () => {
  const s = Math.max((listWrapper?.scrollTop ?? 0) - itemHeight * 10, 0)
  scrollOffset = Math.floor(s / itemHeight / 10) * itemHeight * 10
  scrollOffset = Math.min(totalHeight - itemHeight * keeps, scrollOffset)
  start = Math.min(list.length - keeps - 10, Math.floor(scrollOffset / itemHeight))
  start = Math.max(0, start);
}

const scrollUpHandler = () => {
  const scrollTop = listWrapper.scrollTop
  const clientHeight = listWrapper.clientHeight
  const bottom = totalHeight - clientHeight - scrollTop
  let offsetBottom = Math.floor(bottom / itemHeight / 10) * itemHeight * 9
  offsetBottom = Math.min(totalHeight - itemHeight * keeps, offsetBottom)
  const end = Math.max(keeps, Math.floor(offsetBottom / itemHeight))
  start = list.length - end
  scrollOffset = totalHeight - keeps * itemHeight - offsetBottom
}

const scrollHandler = () => {
  if (listWrapper?.scrollTop >= offset || true) {
    scrollDownHandler()
  } else {
    scrollUpHandler()
  }
}

onMount(() => {
  listWrapper?.addEventListener('scroll', scrollHandler)
})

onDestroy(() => {
  listWrapper?.removeEventListener('scroll', scrollHandler)
})

</script>

<div class="virtual-list"
  bind:this={listWrapper}>
  <div class="virtual-list__inner"
    style="padding-top:{scrollOffset}px;padding-bottom:{paddingBottom}px">
    {#each visibleList as item, index (item)}
      <slot item={item} index={start + index}></slot>
    {/each}
  </div>
</div>

<style>
.virtual-list {
  overflow: auto;
  height: 540px;
}
</style>

// render2/src/components/VirtualList/index.tsx
import { createSignal, createEffect, onCleanup, on, JSXElement, For } from 'solid-js';
import styles from './index.module.css'

interface VirtualListProps<D> {
  list: D[],
  keeps: number,
  itemHeight: number,
  children: (childProps: { index: number, item: D }) => JSXElement,
}

function VirtualList<D extends any>(props: VirtualListProps<D>) {
  const [listWrapper, setListWrapper] = createSignal<HTMLDivElement | null>(null);
  const [startOffset, setStartOffset] = createSignal(0);

  const totalHeight = () => props.list.length * props.itemHeight
  const start = () => Math.floor(startOffset() / props.itemHeight)
  const visibleList = () => {
    return [1,2,3,4]
    // return props.list.slice(start(), start() + props.keeps)
  }

  createEffect(on(() => props.list, () => {
    setStartOffset(0);
  }))

  const scrollHandler = () => {
    const prevCount = 10;
    const scrollTop = listWrapper()?.scrollTop ?? 0;

    let newStartOffset = Math.max(scrollTop - props.itemHeight * prevCount, 0);
    newStartOffset = Math.min(Math.max(0, totalHeight() - props.itemHeight * props.keeps), newStartOffset);

    setStartOffset(newStartOffset);
  };

  createEffect(() => {
    const wrapper = listWrapper();
    if (wrapper) {
      wrapper.addEventListener('scroll', scrollHandler);
      onCleanup(() => {
        wrapper.removeEventListener('scroll', scrollHandler);
      });
    }
  });

  return (
    <div class={'virtual-list ' + styles.virtualList} ref={setListWrapper}>
      <div
        class={'virtual-list__inner ' + styles.virtualListInner}
        style={{
          'padding-top': `${startOffset()}px`,
          'min-height': `${totalHeight()}px`,
        }}
      >
        <For each={visibleList()}>
          {(item, index) => {
            return (
              <div>{index()}</div>
            )
          }}
        </For>
      </div>
    </div>
  );
}

export default VirtualList;
