// src/render/src/components/ResultItem.svelte
<div class="result-item"
  class:selected="{selected}"
  on:click={onEnter}>
  <div class="item-image-wrapper flex-h-v">
    <img src={icon} alt=""/>
  </div>
  <div class="item-info flex-1 flex-col-center">
    <h3 class="item-title text-single-line">{title}</h3>
    <h5 class="item-subtitle color-666 text-sm text-single-line">{subtitle}</h5>
  </div>
</div>

<script lang="ts">
  export let icon: string;
  export let title: string;
  export let subtitle: string;
  export let selected: boolean = false;
  export let onEnter: (event: Event) => void;
</script>

<style>
.result-item {
  scroll-snap-align: start;
  display: flex;
  align-items: center;
  height: 48px;
  max-width: 100%;
  content-visibility: auto;
  contains-intrinsic-size: 48px;
}
.result-item:hover {
  background: #eee;
}
.result-item.selected {
  background: #ddd;
}

.item-image-wrapper {
  width: 48px;
  height: 48px;
  margin-right: 3px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 48px;
}
.item-image-wrapper img {
  width: 32px;
  height: 32px;
}
.item-info {
  max-width: calc(100% - 80px);
}
.item-title {
  font-size: 12px;
  font-weight: bold;
  height: 18px;
}
.item-subtitle {
  font-size: 10px;
  font-weight: normal;
  opacity: 0.6;
  height: 16px;
  white-space: pre;
}
</style>

// render/src/components/ResultItem.vue
<template>
  <div class="resultItem result-item"
    :class="{selected}"
    :data-result-item-index="index"
    @click="$emit('select')"
    @dblclick="$emit('enter')"
  >
    <div class="itemImageWrapper flex-h-v" v-if="icon">
      <img :src="icon" alt=""/>
    </div>
    <div class="itemInfo flex-1 flex-col-center">
      <h3 class="itemTitle text-single-line">{{ title }}</h3>
      <h5 class="itemSubtitle color-666 text-sm text-single-line" v-if="subtitle">{{ subtitle }}</h5>
    </div>
    <div class="shortcutList">
      <div class="shortcutItem" v-if="selected">↵</div>
      <template v-if="!selected && actionKey">
        <div class="shortcutItem">⌘</div>
        <div class="shortcutItem">{{ actionKey }}</div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  index?: number,
  icon?: string,
  title: string,
  subtitle?: string,
  selected?: boolean,
  actionKey?: string
}>()

defineEmits<{
  select: [],
  enter: []
}>()
</script>

<style lang="scss" scoped>
.resultItem {
  scroll-snap-align: start;
  display: flex;
  align-items: center;
  height: 54px;
  max-width: 100%;
  content-visibility: auto;
  contains-intrinsic-size: 54px;
  transition: all .1s;
  padding: 0 12px;
  box-sizing: border-box;
}
.resultItem:hover {
  background-color: light-dark(#c4c4c4, #393939);
}
.resultItem.selected {
  background-color: light-dark(#b4b4b4, #2a2a2a);
}
.itemImageWrapper {
  width: 36px;
  height: 36px;
  margin-right: 6px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 36px;
}
.itemImageWrapper img {
  width: 100%;
  height: 100%;
}
.itemInfo {
  width: 0;
  /* max-width: calc(100% - 90px); */
  flex: 1;
}
.itemTitle {
  font-size: 14px;
  font-weight: bold;
  margin-bottom: 4px;
}
.itemSubtitle {
  font-size: 12px;
  font-weight: normal;
  opacity: 0.6;
  height: 16px;
  white-space: pre;
}
.actionIcon {
  font-size: 16px;
  color: #ccc;
}
.shortcutList {
  display: flex;
  flex-shrink: 0;
  justify-content: flex-end;
  margin-left: 12px;
}
.shortcutItem {
  background: light-dark(#e0e0e0, #3e3e3e);
  height: 20px;
  width: 20px;
  text-align: center;
  line-height: 20px;
  border-radius: 4px;
  font-size: 12px;
  margin-left: 2px;
}
</style>
