// render2/src/components/ResultItem/index.tsx
import { Component, Show } from 'solid-js'
import styles from './index.module.css'

interface Props {
  icon: string,
  title: string,
  subtitle: string,
  selected: boolean,
  index: number,
  onEnter: (event: Event) => void,
  onSelect: (event: Event) => void
}

const ResultItem: Component<Props> = (props) => {
  return (
    <div class={styles.resultItem + ' result-item'}
      classList={{ [styles.selected]: props.selected }}
      data-result-item-index={props.index}
      onMouseOver={props.onSelect}
      onClick={props.onEnter}>
      <div class={styles.itemImageWrapper + ' flex-h-v'}>
        <img src={props.icon} alt=""/>
      </div>
      <div class={styles.itemInfo + ' flex-1 flex-col-center'}>
        <h3 class={styles.itemTitle + ' text-single-line'}>{props.title}</h3>
        <Show when={props.subtitle}>
          <h5 class={styles.itemSubtitle +' color-666 text-sm text-single-line'}>{props.subtitle}</h5>
        </Show>
      </div>
    </div>
  )
}

export default ResultItem

// render/src/components/ResultItem.svelte
<div class="result-item"
  class:selected="{selected}"
  on:click={onEnter}>
  <div class="item-image-wrapper flex-h-v">
    <img src={icon} alt=""/>
  </div>
  <div class="item-info flex-1 flex-col-center">
    <h3 class="item-title text-single-line">{title}</h3>
    <h5 class="item-subtitle color-666 text-sm text-single-line">{subtitle}</h5>
  </div>
</div>

<script lang="ts">
  export let icon: string;
  export let title: string;
  export let subtitle: string;
  export let selected: boolean = false;
  export let onEnter: (event: Event) => void;
</script>

<style>
.result-item {
  scroll-snap-align: start;
  display: flex;
  align-items: center;
  height: 60px;
}
.result-item.selected {
  background: #bbb;
}
.item-image-wrapper {
  width: 60px;
  height: 48px;
  margin-right: 3px;
  display: flex;
  align-items: center;
  justify-content: center;
  min-width: 60px;
}
.item-image-wrapper img {
  width: 42px;
  height: 42px;
}
.item-title {
  font-size: 16px;
  font-weight: normal;
}
.item-subtitle {
  font-size: 12px;
  font-weight: normal;
  opacity: 0.6;
}
</style>
