// render/src/components/VirtualList.vue
<template>
  <div class="virtual-list" ref="listWrapper">
    <div
      class="virtual-list__inner"
      :style="{
        'paddingTop': `${startOffset}px`,
        'minHeight': `${totalHeight}px`,
      }"
    >
      <div class="virtual-list-item" v-for="(item, index) in visibleList" :key="index">
        <slot :item="item" :index="index + start"></slot>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'

const props = withDefaults(defineProps<{
  itemHeight: number,
  list: any[],
  keeps: number,
}>(), {
  itemHeight: 54,
  keeps: 30,
  list: () => []
})

const listWrapper = ref<HTMLElement>()

const startOffset = ref(0)

const totalHeight = computed(() => props.itemHeight * props.list.length)

const start = computed(() => startOffset.value / props.itemHeight)

const visibleList = computed(() => props.list.slice(start.value, start.value + props.keeps))

watch(() => props.list, () => {
  startOffset.value = 0
})

const scrollHandler = () => {
  const prevCount = 10;
  const scrollTop = listWrapper.value?.scrollTop ?? 0;

  let newStartOffset = Math.max(scrollTop - props.itemHeight * prevCount, 0);
  newStartOffset = Math.min(Math.max(0, totalHeight.value - props.itemHeight * props.keeps), newStartOffset);

  startOffset.value = newStartOffset
};

onMounted(() => {
  listWrapper.value?.addEventListener('scroll', scrollHandler)
})

onBeforeUnmount(() => {
  listWrapper.value?.removeEventListener('scroll', scrollHandler)
})
</script>

<style lang="scss" scoped>
.virtual-list {
  overflow: auto;
  max-height: calc(54px * 9);
}
.virtual-list-inner {
  box-sizing: border-box;
}
</style>

// render/src/components/VirtualList.svelte
<script lang="ts">
import { onMount, tick, onDestroy } from 'svelte'

export let list;
export let keeps = 30;
export let itemHeight = 48;

let listWrapper;
let startOffset = 0;
let start = 0;
let totalHeight = 0;

let offset = 0;

let prevList = list;

$: if (prevList !== list) {
  totalHeight = list.length * itemHeight
  offset = 0
  start = 0
  startOffset = 0
  prevList = list
}
$: {
  visibleList = list.slice(start, start + keeps)
}

let visibleList = [];

const scrollDownHandler = () => {
  
  const prevCount = 10

  // 最小值为0，并且前面预留10个位置
  startOffset = Math.max((listWrapper?.scrollTop ?? 0) - itemHeight * prevCount, 0)

  // 最大值不可超过最大滚动高度
  startOffset = Math.min(totalHeight - itemHeight * keeps, startOffset)

  start = Math.floor(startOffset / itemHeight)
}

const scrollUpHandler = () => {
  const scrollTop = listWrapper.scrollTop
  const clientHeight = listWrapper.clientHeight
  const bottom = totalHeight - clientHeight - scrollTop
  let offsetBottom = Math.floor(bottom / itemHeight / 10) * itemHeight * 9
  offsetBottom = Math.min(totalHeight - itemHeight * keeps, offsetBottom)
  const end = Math.max(keeps, Math.floor(offsetBottom / itemHeight))
  start = list.length - end
  startOffset = totalHeight - keeps * itemHeight - offsetBottom
}

const scrollHandler = () => {
  scrollDownHandler()
}

onMount(() => {
  listWrapper?.addEventListener('scroll', scrollHandler)
})

onDestroy(() => {
  listWrapper?.removeEventListener('scroll', scrollHandler)
})

</script>

<div class="virtual-list"
  bind:this={listWrapper}>
  <div class="virtual-list__inner"
    style="padding-top:{startOffset}px;min-height:{totalHeight}px">
    {#each visibleList as item, index (item)}
      <slot item={item} index={start + index}></slot>
    {/each}
  </div>
</div>

<style>
.virtual-list {
  overflow: auto;
  max-height: calc(54px * 9);
}
.virtual-list__inner {
  box-sizing: border-box;
}
::-webkit-scrollbar {
    width: 6px;
    height: 6px;
}
::-webkit-scrollbar-track {
    background: transparent;
}
/* 滚动条滑块 */
::-webkit-scrollbar-thumb {
    background: rgba(0,0,0,0.5);
}
</style>
