// render/src/App.tsx
import React from 'react';
import {
  HashRouter as Router,
  Route
} from 'react-router-dom';
import './App.scss';
import MainView from './components/MainView';
import SettingsView from './components/SettingsView';

class App extends React.Component {

  render () {
    return (
      <div className="App">
        <Router>
          <Route path="/" exact>
            <MainView></MainView>
          </Route>
          <Route path="/settings" exact>
            <SettingsView></SettingsView>
          </Route>
        </Router>
      </div>
    );
  }
}

export default App;

// render2/src/App.tsx
import type { Component } from 'solid-js';
import { HashRouter, Route } from "@solidjs/router";
import MainView from './views/MainView';

import styles from './App.module.css';
import SubListView from './views/SubListView';

const App: Component = () => {
  return (
    <div class={styles.App}>
      <HashRouter>
        <Route path="/plugin/list-view" component={SubListView} />
        <Route path="/" component={MainView} />
      </HashRouter>
    </div>
  );
};

export default App;
