// render/src/components/ResultItemPreview.vue
<template>
  <section class="resultItemPreview">
    <div class="previewWrapper" ref="previewEl"></div>
  </section>
</template>

<script lang="ts" setup>
import { onMounted, ref, watch } from 'vue'

const props = defineProps<{
  html: string | HTMLElement
}>()

const previewEl = ref<HTMLDivElement>()

const renderPreview = () => {
  if (!previewEl.value) return
  if (typeof props.html === 'string') {
    previewEl.value.innerHTML = props.html
  } else {
    previewEl.value.innerHTML = ''
    previewEl.value.appendChild(props.html)
  }
}

watch(() => props.html, renderPreview)

onMounted(() => {
  renderPreview()
})

</script>

<style lang="scss" scoped>
.resultItemPreview {
  box-sizing: border-box;
  flex: 4;
  border-left: 1px solid light-dark(#c0c0c0, #333);
  height: 486px;
  min-height: 486px;
  max-width: 64%;
  overflow: auto;
}
.previewWrapper {
  padding: 12px;
  box-sizing: border-box;
}
</style>

// render2/src/components/ResultItemPreview/index.tsx
import { Component, createEffect, onMount } from "solid-js";
import styles from './index.module.css';

const ResultItemPreview: Component<{ html: string | HTMLElement }> = (props) => {
  let previewEl: HTMLDivElement | null = null
  createEffect(() => {
    if (typeof props.html === 'string') {
      previewEl!.innerHTML = props.html
    } else {
      previewEl!.innerHTML = ''
      previewEl!.appendChild(props.html)
    }
  })
  return (
    <section class={styles.resultItemPreview}>
      <div class={styles.previewWrapper} ref={previewEl!}></div>
    </section>
  )
}

export default ResultItemPreview
